okerr/urls.py
#from django.conf.urls import patterns, include, url
#from django.conf.urls import include, url
from django.urls import path, re_path, include

#from emailusernames.forms import EmailAuthenticationForm
from django.contrib import admin
admin.autodiscover()
import okerrui.views

from django.conf import settings

#urlpatterns = patterns('',
#    # Examples:
#    url(r'^$',okerrui.views.index),
#    url(r'^okerr/',include('okerrui.urls',namespace='okerr')),
#    url(r'^auth/',include('myauth.urls',namespace='myauth')),
#    url(r'^admin/', include(admin.site.urls)),
#    url(r'^i18n/', include('django.conf.urls.i18n')),
#)



urlpatterns = [
    # Examples:
    re_path(r'^$', okerrui.views.index),
    #url(r'^okerr/',include('okerrui.urls' ,namespace='okerr')),
    re_path(r'', include('myauth.urls', namespace='myauth')),
    #url(r'^auth/',include('myauth.urls',namespace='myauth')),
    #re_path(r'^admin/', include(admin.site.urls)),
    # path(r'admin/', admin.site.urls),
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'', include('okerrui.urls' ,namespace='okerr')),
    # url('', include('social_django.urls', namespace='social')),
    re_path(r'moveauth/', include('moveauth.urls' , namespace='moveauth')),
    re_path(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

okerrui/urls.py
#from django.conf.urls import patterns, url
# from django.conf.urls import url
from django.urls import path,re_path

from django.views.generic import TemplateView

from okerrui import views, training


app_name = 'okerrui'

urlpatterns = [

    re_path('oauth2/login/(?P<provider>[^/]+)(?P<suffix>.*)', views.oauth2_login, name='oauth2_login'),
    re_path('oauth2/bind/(?P<provider>[^/]+)(?P<suffix>.*)', views.oauth2_bind, name='oauth2_bind'),
    path('oauth2/callback', views.oauth2_callback, name='oauth2_callback'),
    path('oauth2/select', views.oauth2_select, name='oauth2_select'),
    # url(r'oauth2/info/(<?P<provider>[^/]+)', views.oauth2_info, name='oauth2_info'),


    re_path(r'^sredir/(?P<name>[^/]+)/(?P<path>.*)', views.sredir, name='sredir'),

    path(r'afterlogin', views.afterlogin, name='afterlogin'),
    path(r'', views.index, name='index'),
    re_path(r'^sendsummary/(?P<textid>.+)', views.sendsummary, name='sendsummary'),
#    url(r'^setvpid/(?P<vpid>\d+)$', views.setvpid, name='setvpid'),
#    url(r'^setnovpid$', views.setvpid, name='setnovpid'),
    # url(r'^$', views.index, name='index'),
#    url(r'^indicator/(?P<iid>\d+)$',views.indicator,name='indicator'),
    re_path(r'^indicator/(?P<iid>\d+)/ds$', views.indicator_ds, name='indicatords'),

    re_path(r'^i/(?P<pid>[^/]+)/(?P<iid>.+)$', views.ilocator, name='ilocator'),
    re_path(r'^i/(?P<iid>[^@]+)@(?P<pid>.+)$', views.ilocator, name='ilocatorat'),
    re_path(r'^i/(?P<textid>[^/]+)/?', views.pi, name='pi'),
#    url(r'^uptimelog/(?P<textid>[^/]+)/(?P<iname>.+)$',views.uptimelog,name='uptimelog'),

    path(r'chproject', views.chproject, name='chproject'),

    re_path(r'^log/(?P<textid>[^/]+)$', views.project_log, name='project_log_nocode'),
    re_path(r'^log/(?P<textid>[^/]+)/(?P<codelist>.*)$', views.project_log, name='project_log'),




    re_path(r'^servers/(?P<pid>[^/]+)/?$',views.servers,name='servers'),

    # re_path(r'^servers/(?P<pid>[^/]+)/(?P<prepath>[^/]*)/(?P<path>[^/]+)',views.srvedit, name='srvedit'),
    re_path(r'^servers/(?P<pid>[^/]+)/(?P<prepath>[^/]*)/(?P<path>.+)', views.srvedit, name='srvedit'),

    re_path(r'^add/(?P<tid>.+)', views.add, name='add'),
    re_path(r'^doop/(?P<textid>.+)', views.doop, name='doop'),
    re_path(r'^invitations', views.invitations, name='invitations'),
    re_path(r'^acceptinvite', views.acceptinvite, name='acceptinvite'),
#    re_path(r'^policylist/?',views.policylist,name='policylist'),
    re_path(r'^policy/(?P<textid>[^/]+)/(?P<pname>.+)', views.policy, name='policy'),
    re_path(r'^projectlist/?', views.projectlist, name='projectlist'),
    re_path(r'^project/(?P<pid>.+)', views.project, name='project'),
    re_path(r'^pjson/(?P<pid>.+)', views.pjson, name='pjson'),
    re_path(r'^pdsjson/(?P<textid>[^/]+)/(?P<iname>.+)', views.pdsjson, name='pdsjson'),
    re_path(r'^rawpjson/(?P<tid>.+)', views.rawpjson, name='rawpjson'),
    re_path(r'^rawijson/(?P<iid>\d+)', views.rawijson, name='rawijson'),
    re_path(r'^keys/(?P<pid>[^/]+)/(?P<parentpath>.*)', views.keys, name='keys'),
    re_path(r'^keystext/(?P<pid>\d+)/(?P<parentpath>.*)', views.keystext, name='keystext'),
    re_path(r'^updatevkeys/(?P<pid>\d+)', views.updatevkeys, name='updatevkeys'),
    re_path(r'^resetkeys/(?P<pid>\d+)', views.resetkeys, name='resetkeys'),
    re_path('^toggle_interface_level/(?P<path>.+)', views.toggle_interface_level, name='toggle_interface_level'),

    #    re_path(r'^getkeytree/(?P<textid>[^\/]+)/(?P<path>.*)',views.getkeytree,name='getkeytree'),
    re_path(r'^exportkeyval/(?P<pid>[^\/]+)/(?P<path>.*)', views.exportkeyval, name='exportkeyval'),
    re_path(r'^exportkeyval_raw/(?P<pid>[^\/]+)/(?P<path>.*)', views.exportkeyval_raw, name='exportkeyval_raw'),

    re_path(r'^getnotifications', views.getnotifications, name='getnotifications'),
    re_path(r'^delnotification', views.delnotification, name='delnotification'),

#
#
    re_path(r'^wiznoflap/(?P<textid>[^/]+)/(?P<iname>.+)$', views.wiznoflap, name='wiznoflap'),
    re_path(r'^getsysvar/(?P<varname>.*)', views.getsysvar, name='getsysvar'),


    re_path(r'^getkeyval/(?P<textid>[^\/]+)/(?P<path>.*)', views.getkeyval, name='getkeyval'),
#    re_path(r'^getkeylist/(?P<textid>[^\/]+)/(?P<path>.*)',views.getkeylist,name='getkeylist'),
    re_path(r'^update/?', views.update, name='update'),
    re_path(r'^mirror/?', views.mirror, name='mirror'),
    re_path(r'^getpub/?', views.getpub, name='getpub'),
    re_path(r'^eula', views.eula, name='eula'),
    re_path(r'^motd', views.motd, name='motd'),
    re_path('^firstlogin', views.firstlogin, name='firstlogin'),
    re_path(r'^afterlife', views.afterlife, name='afterlife'),
    re_path(r'^bonusverify', views.bonusverify, name='bonusverify'),
    re_path(r'^tview', TemplateView.as_view(template_name='okerrui/eula.html')),
    re_path(r'^cat', views.cat, name='cat'),



    #
    # # # MODULES # # #
    #

    # STATUSPAGE
    re_path(r'^status/(?P<textid>[^/]+)/(?P<addr>.*)', views.status, name='status'),
    re_path(r'^jstatus/(?P<textid>[^/]+)/(?P<addr>.*)', views.jstatus, name='jstatus'),
    re_path(r'^statuspage/(?P<textid>[^/]+)/(?P<addr>.*)', views.statuspage, name='statuspage'),
    re_path(r'^statussubscribe/(?P<textid>[^/]+)/(?P<addr>[^/]+)/(?P<date>[^/]+)/(?P<email>[^/]+)/(?P<code>.+)',
        views.statussubscribe, name='statussubscribe'),
    re_path(r'^statusunsubscribe/(?P<textid>[^/]+)/(?P<addr>[^/]+)/(?P<date>[^/]+)/(?P<email>[^/]+)/(?P<code>.+)',
        views.statusunsubscribe, name='statusunsubscribe'),



    # TRAINING
    re_path(r'training/(?P<code>.*)', training.training, name='trainingcode'),
    re_path(r'training', training.training, name='training'),

    # DYNDNS
    re_path(r'dyndns/(?P<textid>[^/]+)/(?P<name>.*)', views.dyndns, name='dyndns'),


#    re_path(r'^project_backup/(?P<pid>\d+)?', views.project_backup, name='project_backup'),
#    re_path(r'^email_backup/(?P<pid>\d+)?', views.email_backup, name='email_backup'),





    ### API ###

    re_path(r'^api/indicators/(?P<pid>[^/]+)/?$', views.api_indicators, name='api_indicators'),
    re_path(r'^api/indicators/(?P<pid>[^/]+)/(?P<prefix>.+)', views.api_prefix, name='api_prefix'),
#    re_path(r'^api/getiname/(?P<pid>.+)/(?P<idname>.*)', views.api_getiname, name='api_getiname'),
#    re_path(r'^api/getiid/(?P<pid>.+)/(?P<idname>.*)', views.api_getiid, name='api_getiid'),
    re_path(r'^api/filter/(?P<pid>[^/]+)/(?P<kvlist>.*)', views.api_filter, name='api_filter'),
    re_path(r'^api/tagfilter/(?P<pid>[^/]+)/(?P<tagline>.*)?', views.api_tagfilter, name='api_tagfilter'),
    re_path(r'^api/updatelog/(?P<pid>[^/]+)/(?P<iid>.+)', views.api_updatelog, name='api_updatelog'),
    re_path(r'^api/indicator/(?P<pid>[^/]+)/(?P<iid>.+)', views.api_indicator, name='api_indicator'),
    
    re_path(r'^api/set/(?P<pid>[^/]+)/(?P<iid>.+)', views.api_set, name='api_set'),
    re_path(r'^api/get/(?P<pid>[^/]+)/(?P<iid>.+)/(?P<argname>.+)', views.api_get, name='api_getarg'),
    re_path(r'^api/create/(?P<pid>[^/]+)/(?P<iname>.+)', views.api_create, name='api_create'),
    re_path(r'^api/delete/(?P<pid>[^/]+)/(?P<iname>.+)', views.api_delete, name='api_delete'),
    re_path(r'^api/checkmethods', views.api_checkmethods, name='api_checkmethods'),
    re_path(r'^api/recheck/(?P<pid>[^/]+)/?$', views.api_recheck, name='api_recheck'),

    re_path(r'^api/director/(?P<textid>.*)', views.api_director, name='api_director'),
    re_path(r'^api/check_version/(?P<product>[^/]+)/(?P<version>.+)', views.api_check_version, name='api_check_version'),

    # compatibility aliases
    re_path(r'^api/getarg/(?P<pid>[^/]+)/(?P<iid>.+)/(?P<argname>.+)', views.api_get, name='api_get'),
    re_path(r'^api/setarg/(?P<pid>[^/]+)/(?P<iid>.+)', views.api_set, name='api_set'),

    ### Partner API ####
    re_path(r'^api/partner/check/(?P<partner_id>.+)', views.api_partner_check, name='api_partner_check'),
    re_path(r'^api/partner/list', views.api_partner_list, name='api_partner_list'),
    re_path(r'^api/partner/create', views.api_partner_create, name='api_partner_create'),
    re_path(r'^api/partner/grant', views.api_partner_grant, name='api_partner_grant'),
    re_path(r'^api/partner/revoke', views.api_partner_revoke, name='api_partner_revoke'),

#    re_path(r'^api/partner/preconfigure', views.api_partner_preconfigure, name='api_partner_preconfigure'),


    ### Private API ###
#    re_path(r'^api/sync/?(?P<tstamp>\d+)?', views.api_sync, name='api_sync'),
#    re_path(r'^api/fsync/?(?P<opts>.*)', views.api_fsync, name='api_fsync'),
    re_path(r'^api/plist', views.api_plist, name='api_plist'),
    re_path(r'^api/profile/(?P<pid>.+)', views.api_profile, name='api_profile'),
    re_path(r'^api/myprofile', views.api_myprofile, name='api_myprofile'),

    # re_path(r'^api/project/(?P<tid>.+)', views.api_project, name='api_project'),
#    re_path(r'^api/sdump/?(?P<srid>.+)?', views.api_sdump, name='api_sdump'),
    re_path(r'^api/tproc/get', views.api_tproc_get, name='api_tproc_get'),
    re_path(r'^api/tproc/set', views.api_tproc_set, name='api_tproc_set'),
    re_path(r'^api/listcluster', views.api_listcluster, name='api_listcluster'),
    re_path(r'^api/hostinfo', views.api_hostinfo, name='api_hostinfo'),
    re_path('^api/ip', views.api_ip, name='api_ip'),
    re_path(r'^api/status', views.api_status, name='api_status'),
#    re_path(r'^api/summary', views.api_summary, name='api_summary'),
    re_path(r'^api/setci$', views.api_setci, name='api_setci'),
    re_path(r'^api/groups', views.api_groups, name='api_groups'),
    re_path(r'^api/sensors', views.api_sensors, name='api_sensors'),
    re_path(r'^api/test', views.api_test, name='api_test'),


    re_path(r'^api/admin/list$', views.api_admin_list, name='api_admin_list'),
    re_path(r'^api/admin/cilist$', views.api_admin_cilist, name='api_admin_cilist'),
    re_path(r'^api/admin/export/(?P<email>.*)', views.api_admin_export, name='api_admin_export'),

templates/okerrui/acceptinvite.html
{% extends "okerrui/base.html" %}
{% load i18n %}
{% block content %}

<b>{% trans 'Accept invitation' %}</b>
<p>

{% trans 'You have invitations to projects' %}:
<ul>
{% for inv in pi %}
<li>{{ inv.project.name }} ({% trans 'expires' %}: {{ inv.expires }})
{% endfor %}
</ul>

<form method=post>
{% csrf_token %}
<button class='massButton' name='accept' value='1'>{% trans 'Accept all invitations' %}</button>
<button class='massButton' name='notaccept' value='1'>{% trans 'Maybe later' %}</button>


</form>
<p>

{% url 'okerr:invitations' as invurl %}
{% blocktrans %}
You can alway see and accept your invitations on <a href="{{invurl}}">page</a>.
{% endblocktrans %}
{% endblock %}

templates/okerrui/afterlife.html
{% extends "okerrui/base.html" %}
{% load i18n %}
{% load markup_tags %}

{% block title %}{% trans 'Message of the day' %}{% endblock %}

{% block content %}

    <p>
<h1>{% trans "We are sorry you are leaving :-(" %}</h1>
    </p>
    <p>
    {% trans "Please, let us know what was not so good (or terrible) in okerr?" %}<sup>*</sup>
    </p>

<p>
    <form method=post>
        {% csrf_token %}
        <textarea name="message" rows=10 cols=80 placeholder="{% trans 'Feedback' %}"></textarea><br>
        <input type="text" name="email" placeholder="{% trans 'email address (NOT required)' %}"><br>
        <input type=submit name="continue" value="{% trans 'Continue' %}"><br>
    </form>
</p>
<p class="dull">
    <sup>*</sup> - {% trans 'Feedbacks are read by prepared seasoned adult staff, so do not worry, you can use any words.' %}
</p>
    {% endblock %}

templates/okerrui/motd.html
{% extends "okerrui/base.html" %}
{% load i18n %}
{% load markup_tags %}

{% block title %}{% trans 'Message of the day' %}{% endblock %}

{% block content %}

<center>

<div class="motd">
{{motd|apply_markup:"markdown"}}
</div>

<p>

    <form method=post>
        {% csrf_token %}
        <input type=hidden name="return_url" value="{{return_url}}">
        <input type=hidden name="hash" value="{{hash}}">
        <input type=submit name="continue" value='{% trans 'Continue' %}'>
    </form>

{% endblock %}

templates/okerrui/noproject.html
{% extends "okerrui/base.html" %}
{% load i18n %}
{% load static %}

{% block content %}

    
<div class='header'>
{% trans 'NO PROJECTS' %}
</div>
{% trans 'You have no your project and no access to projects of others.' %}
{% blocktrans %}You can <a href="{{projectlist}}">create your project</a>.{% endblocktrans %}

{% endblock%}

templates/okerrui/projectlinks.html
{% load static %}
{% load i18n %}

<script>
function changeproject(){

    var chs = document.getElementById("chproject_select") 
    var selected = chs.options[chs.selectedIndex].value;
    var chf = document.getElementById("chproject_form") 

    document.getElementById("textid2").value = selected;
    chf.submit()
}
</script>
<form id="chproject_form" action="{% url 'okerr:chproject' %}" method=post>
    {% csrf_token %}
    <input type=hidden name="textid1" value="{{project.get_textid}}">
    <input type=hidden id="textid2" name="textid2" value="">
    <input type=hidden name="path" value="{{request.path}}">   
</form>


&nbsp;

{% if prefix %}
<b>{{prefix}}</b>
{% endif %}

<span>
<select id=chproject_select onchange="changeproject();">
    {% for pt in user.profile.projects_tuples %}
        {% if pt.0 == project.id %}
            <option selected value="{{pt.1}}">{{pt.2}}</option>
        {% else %}
            <option value="{{pt.1}}">{{pt.2}}</option>
        {% endif %}
    {% endfor %}
</select>
</span>

(<acronym title="textid(s): {% for tid in project.projecttextid_set.all %}{{tid}} {%endfor%}">{{project.get_textid}}</acronym>)&nbsp;
<span title='{% trans "indicators" %}'><a href="{% url 'okerr:pi' project.get_textid %}"><img src="{% static 'iflags/OK.png' %}"></a></span>
{% if user.profile.get_jarg_full_interface %}
    <span title="{% trans 'scripts and servers' %}"><a href="{% url 'okerr:servers' project.get_textid %}"><img src="{% static 'computer.png' %}"></a></span>
    <span title="{% trans 'project context' %}"><a href={% url 'okerr:pjson' project.get_textid %}><img src="{% static 'page.png' %}"></a></span>
    <span title="{% trans 'project logs' %}"><a href={% url 'okerr:project_log' project.get_textid '' %}><img src="{% static 'text_columns.png' %}"></a></span>
{% endif %}
<span title="{% trans 'project settings' %}"><a href="{% url 'okerr:project' project.get_textid %}"><img src="{% static 'wrench.png' %}"></a></span>

templates/okerrui/projectlist.html
{% extends "okerrui/base.html" %}
{% load i18n %}
{% load static %}

{% block content %}



    <b>{% trans 'Your Projects' %}</b>
    <table>
        <tr class=title>
            <td>{% trans 'Title' %}
            <td>{% trans 'Statistics' %}
            <td>{% trans 'Text ID' %}
            <td>{% trans 'Owner' %}
            <td>{% trans 'Members' %}
            <td>{% trans 'Manage project' %}
            <td>{% trans 'Manage indicators' %}
            
    {% for t in projects %}
        {% if forloop.counter|divisibleby:2 %}
            <tr bgcolor="eeeeee">
        {% else %}
        <tr>
        {% endif %}
            
            <td>
                <a href="{% url 'okerr:project' t.textid %}">{{t.name}}</a>
            <td><div class="tooltip">{{ t.stats.ni }} / {{ t.stats.enabled }}
                    <span class="tooltiptext">Total {{ t.stats.ni }} indicators, {{ t.stats.enabled }} enabled</span>
                </div>
            <td>
                {% for tid in t.textids %}
                    <a href="{% url 'okerr:project' tid %}">{{ tid }}</a>
                {% endfor %}
                
            <td>{{ t.owner }}            
            <td>{{ t.nmembers }}
            <td>{{ t.tadmin }}
            <td>{{ t.iadmin }}
        </tr>
    {%endfor%}
    </table>

    <p>

    {# add project #}
    <form action="" method="post">
    {% csrf_token %}
    <table>
    <tr>
        <td>
            {% trans 'Project name' %}:
        </td>
        <td>
            <input type=text name="name">
        </td>
    </tr>

    </table>
    
    <button class='massButton' name='add' value='1'>{% trans 'Add' %}</button>

    </form>

{% endblock %}

templates/okerrui/statuspage.html
{% extends "okerrui/base.html" %}
{% load i18n %}
{% load static %}
{% load markup_tags %}

{% block content %}


{% with project=project %}
    {% include 'okerrui/projectlinks.html' %}
{% endwith %}

    
    <b>{% trans "Status Page" %}:</b> {{sp.addr}}<br>
   
   
    <div class='smalledit'>
    <h2>{% trans 'Properties' %}</h2>
    <form action="{% url 'okerr:statuspage' project.get_textid sp.addr %}" method="post">
    <table>
        <tr>
            <td>{% trans 'Address' %}</td>
            <td><input type=text name="addr" value="{{ sp.addr }}"></td>
            <td>
                <a href="{% url 'okerr:status' project.get_textid sp.addr %}">{% url 'okerr:status' project.get_textid sp.addr %}</a>
            </td>
        </tr>

        <tr>
            <td>{% trans 'Title' %}
            <td><input type=text name="title" value="{{ sp.title }}">
            <td><i>{% trans 'status page title' %}</i></td>
        </tr>


         <tr>
            <td>{% trans 'Public' %}
            <td>
            {% if sp.public %}
                <input type="checkbox" name="public" value="1" checked>
            {% else %}
                <input type="checkbox" name="public" value="1">
            {% endif %}
            </td>
        </tr>


         <tr>
            <td>{% trans 'User can subscribe' %}
            <td>
            {% if sp.can_subscribe %}
                <input type="checkbox" name="can_subscribe" value="1" checked>
            {% else %}
                <input type="checkbox" name="can_subscribe" value="1">
            {% endif %}
            {{nsubscribers}} {% trans 'subscriber(s)' %} (max: {{maxsubscribers}})
            </td>
        </tr>


        <tr>
            <td>{% trans 'Description' %}
            <td colspan=2><textarea name="desc" cols=80>{{ sp.desc }}</textarea></td>
        </tr>


    </table>

        {% csrf_token %}

        <input type="hidden" name="statuspage_edit" value="1" />
        
        <button class='massButton' name='apply' value='1'>{% trans 'Apply' %}</button>
        <button class='massButton' name='delete' value='1' onclick="return confirm('Are you sure?')">{% trans 'Delete' %}</button>

    </form>

        <h2>{% trans 'Indicators' %}</h2>

<datalist id="chapters_list">
{% for chapter in chapters.keys %}
  <option value="{{chapter}}">
{% endfor %}
</datalist>


    {% for chapter, silist in chapters.items %}
        {% if chapter %}
            <h3>{{chapter}}</h3>
        {% else %}
            <h3>{% trans 'No chapter' %}</h3>
        {% endif %}
    
        {% for si in silist %}
            <details>
                <summary><b>{{si.title}}</b> ({{si.indicator.name}})</summary>
                    <form action="{% url 'okerr:statuspage' project.get_textid sp.addr %}" method="post">
                    {% csrf_token %}
                    <input type=hidden name=indicator value="{{si.indicator.name}}">
                    <table>
                    <tr>
                        <td>{% trans 'Indicator' %}:</td>
                        <td><a href="{% url 'okerr:ilocator' sp.project.get_textid si.indicator.name %}">{{ si.indicator.name }}</a></td>
                    </tr>
                    <tr>
                        <td>{% trans 'Title' %}:</td>
                        <td><input type=text name=title value="{{ si.title }}"></td>
                    </tr>
                    <tr>
                        <td>{% trans 'Chapter' %}:</td>
                        <td>
                        <input type="text" name="chapter" autocomplete="off" list="chapters_list" placeholder="{% trans 'New chapter name' %}" value="{{si.chapter}}">
                        </td>
                    </tr>
                    <tr>
                        <td>{% trans 'Weight' %}:</td>
                        <td><input type=text name=weight value="{{ si.weight }}"></td>
                    </tr>

                    <tr>
                        <td>{% trans 'Details' %}:</td>
                        <td>                        
                        {% if si.details %}
                            <input type="checkbox" name="details" value="1" checked>
                        {% else %}
                            <input type="checkbox" name="details" value="1">
                        {% endif %}
                        </td>
                    </tr>


                    <tr>
                        <td>{% trans 'Desc' %}:</td>
                        <td><textarea name=desc cols=40>{{ si.desc }}</textarea></td>
                    </tr>  
                    </table>
                    <button class='massButton' name='chsi' value='1'>{% trans 'Change' %}</button>
                    <button class='massButton' name='delsi' value='1' onclick="return confirm('Are you sure?')">{% trans 'Delete' %}</button>
                    </form>
            </details>
        {% endfor %}
    
    {% endfor %} <!-- chapters -->

    <!-- add new indicator -->

    <br>
    <form action="{% url 'okerr:statuspage' project.get_textid sp.addr %}" method="post">
        {% csrf_token %}
        <table>
            <tr>
                <td>
                    {% trans 'Add indicator' %}:
                </td>
                <td>
                    <select name="newindicator">
                    {% for i in project.indicator_set.all %}
                    <option value="{{i.name}}">{{i.name}}</option>
                    {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    {% trans 'Chapter' %}:
                </td>
                <td>
                    <input type="text" name="chapter" autocomplete="off" list="chapters_list" placeholder="{% trans 'New chapter name' %}" value="{{last_chapter}}">
                </td>
            </tr>
            <tr>
                <td>
                    <input type="hidden" name="newindicator_add" value="1" />
                    <button class='massButton' name='Add' value='1'>{% trans 'Add' %}</button>
                </td>
            </tr>
        </table>

    </form>
    
    <h2>{% trans 'Blog' %}</h2>
    
    {% if blogrecord %}
        {% trans 'Last record' %}:
        <div class="sp_indicator">
            {{blogrecord.text|apply_markup:"markdown"}} 
            <div class="dulldate">{{blogrecord.created}}</div>
        </div>
        <form name=delblog method="post">
            {% csrf_token %}
            <input type=submit name="delblog" value="{% trans 'Delete' %}">
        </form>
    {% endif %}
    
    {% if draft %}
        {% trans 'Preview' %}:
        <div class="sp_indicator">
            {{draft|apply_markup:"markdown"}} 
            <div class="dulldate">{% now "d M Y H:i:s" %}</div>
        </div>
    {% endif %}
    
    <form method=post>
        {% csrf_token %}
        <textarea cols=80 name=blogpost>{{draft}}</textarea>
        <br>
   
        <button class='massButton' name='add' value='1'>{% trans 'Add' %}</button>
        <button class='massButton' name='preview' value='1'>{% trans 'Preview' %}</button>

        <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">{% trans 'Markdown cheatsheet' %}</a>
    
    </form>
    
    </div> <!-- smalledit -->
{% endblock %}

templates/okerrui/uptimelog.html
{% extends "okerrui/base.html" %}
{% load i18n %}
{% load static %}
{% load age %}

{% block title%}{{i.name}}{%endblock%}

{% block content %}
{% trans 'Uptime log for' %} <a href="{% url 'okerr:ilocator' i.project.get_textid i.name %}">{{i.name}}</a>

<table class="humantable">
{% for s in changes %}
    <tr>
        <td>{{s.created}}</td>
        <td>{{s.old}} ({{s.duration}}) > {{s.new}}</td>
    </tr>
{% endfor %}

</table>
{% endblock %}