okerr/urls.py
#from django.conf.urls import patterns, include, url
#from django.conf.urls import include, url
from django.urls import path, re_path, include

#from emailusernames.forms import EmailAuthenticationForm
from django.contrib import admin
admin.autodiscover()
import okerrui.views

from django.conf import settings

#urlpatterns = patterns('',
#    # Examples:
#    url(r'^$',okerrui.views.index),
#    url(r'^okerr/',include('okerrui.urls',namespace='okerr')),
#    url(r'^auth/',include('myauth.urls',namespace='myauth')),
#    url(r'^admin/', include(admin.site.urls)),
#    url(r'^i18n/', include('django.conf.urls.i18n')),
#)



urlpatterns = [
    # Examples:
    re_path(r'^$', okerrui.views.index),
    #url(r'^okerr/',include('okerrui.urls' ,namespace='okerr')),
    re_path(r'', include('myauth.urls', namespace='myauth')),
    #url(r'^auth/',include('myauth.urls',namespace='myauth')),
    #re_path(r'^admin/', include(admin.site.urls)),
    # path(r'admin/', admin.site.urls),
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'', include('okerrui.urls' ,namespace='okerr')),
    # url('', include('social_django.urls', namespace='social')),
    re_path(r'moveauth/', include('moveauth.urls' , namespace='moveauth')),
    re_path(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

okerrui/urls.py
#from django.conf.urls import patterns, url
# from django.conf.urls import url
from django.urls import path,re_path

from django.views.generic import TemplateView

from okerrui import views, training


app_name = 'okerrui'

urlpatterns = [

    re_path('oauth2/login/(?P<provider>[^/]+)(?P<suffix>.*)', views.oauth2_login, name='oauth2_login'),
    re_path('oauth2/bind/(?P<provider>[^/]+)(?P<suffix>.*)', views.oauth2_bind, name='oauth2_bind'),
    path('oauth2/callback', views.oauth2_callback, name='oauth2_callback'),
    path('oauth2/select', views.oauth2_select, name='oauth2_select'),
    # url(r'oauth2/info/(<?P<provider>[^/]+)', views.oauth2_info, name='oauth2_info'),


    re_path(r'^sredir/(?P<name>[^/]+)/(?P<path>.*)', views.sredir, name='sredir'),

    path(r'afterlogin', views.afterlogin, name='afterlogin'),
    path(r'', views.index, name='index'),
    re_path(r'^sendsummary/(?P<textid>.+)', views.sendsummary, name='sendsummary'),
#    url(r'^setvpid/(?P<vpid>\d+)$', views.setvpid, name='setvpid'),
#    url(r'^setnovpid$', views.setvpid, name='setnovpid'),
    # url(r'^$', views.index, name='index'),
#    url(r'^indicator/(?P<iid>\d+)$',views.indicator,name='indicator'),
    re_path(r'^indicator/(?P<iid>\d+)/ds$', views.indicator_ds, name='indicatords'),

    re_path(r'^i/(?P<pid>[^/]+)/(?P<iid>.+)$', views.ilocator, name='ilocator'),
    re_path(r'^i/(?P<iid>[^@]+)@(?P<pid>.+)$', views.ilocator, name='ilocatorat'),
    re_path(r'^i/(?P<textid>[^/]+)/?', views.pi, name='pi'),
#    url(r'^uptimelog/(?P<textid>[^/]+)/(?P<iname>.+)$',views.uptimelog,name='uptimelog'),

    path(r'chproject', views.chproject, name='chproject'),

    re_path(r'^log/(?P<textid>[^/]+)$', views.project_log, name='project_log_nocode'),
    re_path(r'^log/(?P<textid>[^/]+)/(?P<codelist>.*)$', views.project_log, name='project_log'),




    re_path(r'^servers/(?P<pid>[^/]+)/?$',views.servers,name='servers'),

    # re_path(r'^servers/(?P<pid>[^/]+)/(?P<prepath>[^/]*)/(?P<path>[^/]+)',views.srvedit, name='srvedit'),
    re_path(r'^servers/(?P<pid>[^/]+)/(?P<prepath>[^/]*)/(?P<path>.+)', views.srvedit, name='srvedit'),

    re_path(r'^add/(?P<tid>.+)', views.add, name='add'),
    re_path(r'^doop/(?P<textid>.+)', views.doop, name='doop'),
    re_path(r'^invitations', views.invitations, name='invitations'),
    re_path(r'^acceptinvite', views.acceptinvite, name='acceptinvite'),
#    re_path(r'^policylist/?',views.policylist,name='policylist'),
    re_path(r'^policy/(?P<textid>[^/]+)/(?P<pname>.+)', views.policy, name='policy'),
    re_path(r'^projectlist/?', views.projectlist, name='projectlist'),
    re_path(r'^project/(?P<pid>.+)', views.project, name='project'),
    re_path(r'^pjson/(?P<pid>.+)', views.pjson, name='pjson'),
    re_path(r'^pdsjson/(?P<textid>[^/]+)/(?P<iname>.+)', views.pdsjson, name='pdsjson'),
    re_path(r'^rawpjson/(?P<tid>.+)', views.rawpjson, name='rawpjson'),
    re_path(r'^rawijson/(?P<iid>\d+)', views.rawijson, name='rawijson'),
    re_path(r'^keys/(?P<pid>[^/]+)/(?P<parentpath>.*)', views.keys, name='keys'),
    re_path(r'^keystext/(?P<pid>\d+)/(?P<parentpath>.*)', views.keystext, name='keystext'),
    re_path(r'^updatevkeys/(?P<pid>\d+)', views.updatevkeys, name='updatevkeys'),
    re_path(r'^resetkeys/(?P<pid>\d+)', views.resetkeys, name='resetkeys'),
    re_path('^toggle_interface_level/(?P<path>.+)', views.toggle_interface_level, name='toggle_interface_level'),

    #    re_path(r'^getkeytree/(?P<textid>[^\/]+)/(?P<path>.*)',views.getkeytree,name='getkeytree'),
    re_path(r'^exportkeyval/(?P<pid>[^\/]+)/(?P<path>.*)', views.exportkeyval, name='exportkeyval'),
    re_path(r'^exportkeyval_raw/(?P<pid>[^\/]+)/(?P<path>.*)', views.exportkeyval_raw, name='exportkeyval_raw'),

    re_path(r'^getnotifications', views.getnotifications, name='getnotifications'),
    re_path(r'^delnotification', views.delnotification, name='delnotification'),

#
#
    re_path(r'^wiznoflap/(?P<textid>[^/]+)/(?P<iname>.+)$', views.wiznoflap, name='wiznoflap'),
    re_path(r'^getsysvar/(?P<varname>.*)', views.getsysvar, name='getsysvar'),


    re_path(r'^getkeyval/(?P<textid>[^\/]+)/(?P<path>.*)', views.getkeyval, name='getkeyval'),
#    re_path(r'^getkeylist/(?P<textid>[^\/]+)/(?P<path>.*)',views.getkeylist,name='getkeylist'),
    re_path(r'^update/?', views.update, name='update'),
    re_path(r'^mirror/?', views.mirror, name='mirror'),
    re_path(r'^getpub/?', views.getpub, name='getpub'),
    re_path(r'^eula', views.eula, name='eula'),
    re_path(r'^motd', views.motd, name='motd'),
    re_path('^firstlogin', views.firstlogin, name='firstlogin'),
    re_path(r'^afterlife', views.afterlife, name='afterlife'),
    re_path(r'^bonusverify', views.bonusverify, name='bonusverify'),
    re_path(r'^tview', TemplateView.as_view(template_name='okerrui/eula.html')),
    re_path(r'^cat', views.cat, name='cat'),



    #
    # # # MODULES # # #
    #

    # STATUSPAGE
    re_path(r'^status/(?P<textid>[^/]+)/(?P<addr>.*)', views.status, name='status'),
    re_path(r'^jstatus/(?P<textid>[^/]+)/(?P<addr>.*)', views.jstatus, name='jstatus'),
    re_path(r'^statuspage/(?P<textid>[^/]+)/(?P<addr>.*)', views.statuspage, name='statuspage'),
    re_path(r'^statussubscribe/(?P<textid>[^/]+)/(?P<addr>[^/]+)/(?P<date>[^/]+)/(?P<email>[^/]+)/(?P<code>.+)',
        views.statussubscribe, name='statussubscribe'),
    re_path(r'^statusunsubscribe/(?P<textid>[^/]+)/(?P<addr>[^/]+)/(?P<date>[^/]+)/(?P<email>[^/]+)/(?P<code>.+)',
        views.statusunsubscribe, name='statusunsubscribe'),



    # TRAINING
    re_path(r'training/(?P<code>.*)', training.training, name='trainingcode'),
    re_path(r'training', training.training, name='training'),

    # DYNDNS
    re_path(r'dyndns/(?P<textid>[^/]+)/(?P<name>.*)', views.dyndns, name='dyndns'),


#    re_path(r'^project_backup/(?P<pid>\d+)?', views.project_backup, name='project_backup'),
#    re_path(r'^email_backup/(?P<pid>\d+)?', views.email_backup, name='email_backup'),





    ### API ###

    re_path(r'^api/indicators/(?P<pid>[^/]+)/?$', views.api_indicators, name='api_indicators'),
    re_path(r'^api/indicators/(?P<pid>[^/]+)/(?P<prefix>.+)', views.api_prefix, name='api_prefix'),
#    re_path(r'^api/getiname/(?P<pid>.+)/(?P<idname>.*)', views.api_getiname, name='api_getiname'),
#    re_path(r'^api/getiid/(?P<pid>.+)/(?P<idname>.*)', views.api_getiid, name='api_getiid'),
    re_path(r'^api/filter/(?P<pid>[^/]+)/(?P<kvlist>.*)', views.api_filter, name='api_filter'),
    re_path(r'^api/tagfilter/(?P<pid>[^/]+)/(?P<tagline>.*)?', views.api_tagfilter, name='api_tagfilter'),
    re_path(r'^api/updatelog/(?P<pid>[^/]+)/(?P<iid>.+)', views.api_updatelog, name='api_updatelog'),
    re_path(r'^api/indicator/(?P<pid>[^/]+)/(?P<iid>.+)', views.api_indicator, name='api_indicator'),
    
    re_path(r'^api/set/(?P<pid>[^/]+)/(?P<iid>.+)', views.api_set, name='api_set'),
    re_path(r'^api/get/(?P<pid>[^/]+)/(?P<iid>.+)/(?P<argname>.+)', views.api_get, name='api_getarg'),
    re_path(r'^api/create/(?P<pid>[^/]+)/(?P<iname>.+)', views.api_create, name='api_create'),
    re_path(r'^api/delete/(?P<pid>[^/]+)/(?P<iname>.+)', views.api_delete, name='api_delete'),
    re_path(r'^api/checkmethods', views.api_checkmethods, name='api_checkmethods'),
    re_path(r'^api/recheck/(?P<pid>[^/]+)/?$', views.api_recheck, name='api_recheck'),

    re_path(r'^api/director/(?P<textid>.*)', views.api_director, name='api_director'),
    re_path(r'^api/check_version/(?P<product>[^/]+)/(?P<version>.+)', views.api_check_version, name='api_check_version'),

    # compatibility aliases
    re_path(r'^api/getarg/(?P<pid>[^/]+)/(?P<iid>.+)/(?P<argname>.+)', views.api_get, name='api_get'),
    re_path(r'^api/setarg/(?P<pid>[^/]+)/(?P<iid>.+)', views.api_set, name='api_set'),

    ### Partner API ####
    re_path(r'^api/partner/check/(?P<partner_id>.+)', views.api_partner_check, name='api_partner_check'),
    re_path(r'^api/partner/list', views.api_partner_list, name='api_partner_list'),
    re_path(r'^api/partner/create', views.api_partner_create, name='api_partner_create'),
    re_path(r'^api/partner/grant', views.api_partner_grant, name='api_partner_grant'),
    re_path(r'^api/partner/revoke', views.api_partner_revoke, name='api_partner_revoke'),

#    re_path(r'^api/partner/preconfigure', views.api_partner_preconfigure, name='api_partner_preconfigure'),


    ### Private API ###
#    re_path(r'^api/sync/?(?P<tstamp>\d+)?', views.api_sync, name='api_sync'),
#    re_path(r'^api/fsync/?(?P<opts>.*)', views.api_fsync, name='api_fsync'),
    re_path(r'^api/plist', views.api_plist, name='api_plist'),
    re_path(r'^api/profile/(?P<pid>.+)', views.api_profile, name='api_profile'),
    re_path(r'^api/myprofile', views.api_myprofile, name='api_myprofile'),

    # re_path(r'^api/project/(?P<tid>.+)', views.api_project, name='api_project'),
#    re_path(r'^api/sdump/?(?P<srid>.+)?', views.api_sdump, name='api_sdump'),
    re_path(r'^api/tproc/get', views.api_tproc_get, name='api_tproc_get'),
    re_path(r'^api/tproc/set', views.api_tproc_set, name='api_tproc_set'),
    re_path(r'^api/listcluster', views.api_listcluster, name='api_listcluster'),
    re_path(r'^api/hostinfo', views.api_hostinfo, name='api_hostinfo'),
    re_path('^api/ip', views.api_ip, name='api_ip'),
    re_path(r'^api/status', views.api_status, name='api_status'),
#    re_path(r'^api/summary', views.api_summary, name='api_summary'),
    re_path(r'^api/setci$', views.api_setci, name='api_setci'),
    re_path(r'^api/groups', views.api_groups, name='api_groups'),
    re_path(r'^api/sensors', views.api_sensors, name='api_sensors'),
    re_path(r'^api/test', views.api_test, name='api_test'),


    re_path(r'^api/admin/list$', views.api_admin_list, name='api_admin_list'),
    re_path(r'^api/admin/cilist$', views.api_admin_cilist, name='api_admin_cilist'),
    re_path(r'^api/admin/export/(?P<email>.*)', views.api_admin_export, name='api_admin_export'),

templates/503.html
Maintenance. Please come back in 10-15 minutes...

templates/alert-ad.html
<div class="ad">
<a href="https://okerr.com">okerr</a> monitoring system 
</div>

templates/alert-email.html
<html>
    <head>
        {% include 'mail-css.html' %}
    </head>
    <body>
    <h1><font color="#666666">okerr alert</font></h1>
    id: {{alertid}}
    for: {{user.username}}<br>
    generated on {{hostname}} at {% now "d M Y H:i:s" %}
    <p>
    <h2>Alerts</h2>
    <table>
    {% for a in alerts %}
        <tr>
        <td>{{a.created|date:"d M Y H:i:s"}}</td>
        <td><a href="{{siteurl}}{% url 'okerr:ilocator' a.indicator.project.get_textid a.indicator.name %}">{{a.indicator.name}}</a></td>
        <td>{{a.message}}</td>
        </tr>
    {% endfor %}
    </table>

    <h2>Project(s) summary</h2>
    <table>
    {% for p in profile.projects %}
        <tr>
            <td>{{p.name}}</td>
            <td>{{p.stringstat}}</td>
        </tr>
    {% endfor %}
    </table>


    {% include "alert-ad.html" %}

    {% include "bulkmail.html" %}

    </body>
</html>

templates/dummy.html
{% trans 'Default' %}
{% trans 'silent' %}
{% trans 'pending' %}
{% trans 'Name' %}
{% trans 'Check Method' %}
{% trans 'status' %}
{% trans 'Details' %}
{% trans 'Changed' %}
{% trans 'Updated' %}
{% trans 'Disabled' %}
{% trans 'Problem:' %}
{% trans 'Silent' %}
{% trans 'Expected' %}
{% trans 'Scheduled' %}
{% trans 'maintenance' %}
{% trans 'passive' %}
{% trans 'subscribe' %}
{% trans 'star' %}

templates/invite-email.html
<html>
<h1><font color="#666666">okerr invite</font></h1>

{{user.username}} invites you to join his project {{project.name}} on okerr!<br>

As soon as you will <a href="{{regurl}}">register</a> (if you didn't registered already) and <a href="{{loginurl}}">login</a>, you will find invitation in 'Invitations' part of user interface.
</html>

templates/newpassword.html
<html>
<head>
    {% include 'mail-css.html' %}
</head>
    <body>
    <h1>okerr password recovery</h1>

    Your username is: {{username}}<br>
    Your new auto-generated password is: {{password}}<br>
    Please change password after sign-in.<br>
    Log in page: {{loginurl}}<br>
    <br>
    Thank you!
    
    {% include "alert-ad.html" %}
    {% include "bulkmail.html" %}
    </body>
</html>

templates/password-recovery.html
<html>
    <head>
        {% include 'mail-css.html' %}
    </head>
    <body>
    <h1>Okerr password recovery</h1>
    Thanks for using Okerr!<br>
    Your verification code is: {{code}}, please enter it on <a href="{{vlink}}?email={{email}}&code={{code}}">verification</a> page.

    {% include "alert-ad.html" %}
    {% include "bulkmail.html" %}

    </body>
</html>

templates/patrol-report.html
<html>
<h1><font color="#666666">okerr IMPORTANT alert</font></h1>
generated on {{hostname}} at {% now "d M Y H:i:s" %}
<p>
<h2>Patrol report</h2>


{% if maxindicators %}
    <h3>max_indicators limit</h3>
    max_indicators ({{profile.get_maxindicators}}) limit reached. Following indicators are disabled automatically.
    <ul>
        {% for i in maxindicators %}
            <li><a href="{{siteurl}}{% url 'okerr:ilocator' i.project.get_textid i.name %}">{{i.name}}</a>
        {% endfor %}
    </ul>
{% endif %}
 
{% if minperiod %}
    <h3>minperiod limit</h3>
    Following indicators are disabled automatically (minperiod: {{profile.get_minperiod}}):
    <ul>
        {% for i in minperiod %}
            <li><a href="{{siteurl}}{% url 'okerr:ilocator' i.project.get_textid i.name %}">{{i.name}}</a>
                (policy: {{i.policy.name}} period: {{i.policy.period}})
        {% endfor %}
    </ul>    
{% endif %}


{% if teamsize %}
    <h3>teamsize limit</h3>
    Following projects are limited automatically (teamsize: {{profile.get_teamsize}}):
    <ul>
        {% for p in teamsize %}
            <li>
                <a href="{{siteurl}}{% url 'okerr:pi' p.get_textid %}">{{p.name}}</a> 
                textid: <a href="{{siteurl}}{% url 'okerr:pi' p.get_textid %}">{{p.get_textid}}</a>
                ({{p.nmembers}} members)
        {% endfor %}
    </ul>    
{% endif %}

{% if maxprojects %}
    <h3>teamsize limit</h3>
    Following projects are limited automatically (maxprojects: {{profile.get_maxprojects}}):
    <ul>
        {% for p in maxprojects %}
            <li>
                <a href="{{siteurl}}{% url 'okerr:pi' p.get_textid %}">{{p.name}}</a>
                textid: <a href="{{siteurl}}{% url 'okerr:pi' p.get_textid %}">{{p.get_textid}}</a>
                ({{p.nmembers}} members)
        {% endfor %}
    </ul>    
{% endif %}


{% if unlimited %}
    <h3>Limitations removed</h3>
    Limitations are removed from following projects:
    <ul>
        {% for p in unlimited %}
            <li>
                <a href="{{siteurl}}{% url 'okerr:pi' p.get_textid %}">{{p.name}}</a>
                textid: <a href="{{siteurl}}{% url 'okerr:pi' p.get_textid %}">{{p.get_textid}}</a>
                    ({{p.nmembers}} members)
        {% endfor %}
    </ul>    
{% endif %}

You can upgrade your membership, or order perk, or disable/delete other indicators/projects to enable/unlimit these indicators/projects.
<br>

</html>

templates/statuspage-subscribe.html
{% load i18n %}
<html>
<h1><font color="#666666">{% trans 'Subscribe to status page' %} {{sp.title}}</font></h1>
{% trans 'generated on' %} {{hostname}} at {% now "d M Y H:i:s" %}
<p>
{% trans 'Please confirm subscription to status page' %} {{sp.title}}: <a href="{{base_url}}{% url 'okerr:statussubscribe' project.get_textid sp.addr datecode email code %}">{% trans 'Confirm' %}</a>.
<p>
{% trans 'After confirmation you will get email notifications after new blog post at address' %}: <a href="{{prefix}}{% url 'okerr:status' project.get_textid sp.addr %}">{{prefix}}{% url 'okerr:status' project.get_textid sp.addr %}</a>
</html>

templates/statuspage-update.html
{% load i18n %}
{% load markup_tags %}

<html>
<h1><font color="#666666">{% trans 'Updated status page' %} {{sp.title}}</font></h1>
{% trans 'generated on' %} {{hostname}} at {% now "d M Y H:i:s" %}

<div style="border: 3px dashed #666; background: #ccc; padding: 10px;">
{{text|apply_markup:"markdown"}} 
</div>
<p>
{% trans 'Status page' %}: <a href="{{base_url}}{% url 'okerr:status' project.get_textid sp.addr %}">{{ sp.title }}</a>.
</p>
<p>
{% trans 'You can' %} <a href="{{base_url}}{% url 'okerr:statusunsubscribe' project.get_textid sp.addr datecode email code %}">{% trans 'Unsubscribe' %}</a>.
</p>
</html>

templates/summary-1project-email.html
<h2>Project: {{project.name}}</h2>

{% if project.indicators_deep %}
oldest update: {{project.updatemin}} ({{project.updatemin|timesince}})<br>
newest update: {{project.updatemax}} ({{project.updatemax|timesince}})<br>
<p>


{% if project.req_attention %}                    
    <h3>ATTENTION</h3>
        <table border=0 cellspacing=0>
            <tr>
                <th>Flags
                <th>Name
                <th>Details
                <th>Age
                <th>Status Age
            {% for i in project.indicators_deep.all %}        
                
                {% if not i.disabled and 'ATTENTION' in i.tags %}                 

                    {% if i.okerrm == 'ERR' %}
                    <tr bgcolor="{% cycle '#ffaaaa' '#ffbbbb' %}">
                    {% else %}
                    <tr bgcolor="{% cycle '#eeeeee' '#dddddd' %}">
                    {% endif %}
                                    
                        <td>{% for f in i.flags %}
                            <img src="http://static.okerr.com/iflags/{{f}}.png" alt="flag: {{f}}">
                        {% endfor %}
                        <td><a href="{{siteurl}}{% url 'okerr:ilocator' i.project.get_textid i.name %}">{{i.name}}</a>
                        <td>{{ i.briefdetails }}
                        <td>{{ i.age_short }}
                        <td>{{ i.statusage_short }}                
                    </tr>
            {% endif %}
        {%endfor%}
        </table>    
<p>
{% else %}
No indicators requires immediate attention
{% endif %}

<h3>All Indicators</h3>
    <table border=0 cellspacing=0>
        <tr>
            <th>Flags
            <th>Name
            <th>Details
            <th>Age
            <th>Status Age
        {% for i in project.indicators_deep %}
        
        {% if not i.disabled %}
            
            {% if i.okerrm == 'ERR' %}
            <tr bgcolor="{% cycle '#ffaaaa' '#ffbbbb' %}">
            {% else %}
            <tr bgcolor="{% cycle '#eeeeee' '#dddddd' %}">
            {% endif %}

            
            
            <td>{% for f in i.flags %}
                    <img src="http://static.okerr.com/iflags/{{f}}.png" alt="flag: {{f}}">
                {% endfor %}
            <td><a href="{{siteurl}}{% url 'okerr:ilocator' i.project.get_textid i.name %}">{{i.name}}</a>
            <td>{{ i.briefdetails }}
            <td>{{ i.age_short }}
            <td>{{ i.statusage_short }}
            </tr>
        {% endif %}
    {%endfor%}
    </table>
{% else %}
No indicators in this project.
{% endif %}

templates/summary-allprojects-email.html
<html>
<head>
    {% include 'mail-css.html' %}
</head>

<h1>okerr summary</h1>
for: {{profile.user.username}}<br>
remark: {{remark}}<br>
host: {{hostname}}<br>

{% for project in profile.projects %}
{% include "summary-1project-email.html" %}
{% endfor %}

{% include "alert-ad.html" %}
{% include "bulkmail.html" %}

</html>

templates/summary-project-email.html
<html>
<head>
    {% include 'mail-css.html' %}
</head>
<h1>okerr summary</h1>
for: {{username}}<br>
remark: {{remark}}<br>
host: {{hostname}}<br>

{% include "summary-1project-email.html" %}

{% include "alert-ad.html" %}
{% include "bulkmail.html" %}

</html>

templates/warnexpire-email.html
<html>
<h1><font color="#666666">okerr IMPORTANT alert</font></h1>
for: {{user.username}}<br>
generated on {{hostname}} at {% now "d M Y H:i:s" %}
<p>
<h2>Membership expiration alert</h2>
Your membership in group {{membership.groupname}} expires soon.
<br>
Expiration date/time: {{membership.expires}}
<br>
Time left: {{timeleft}}
<p>

You are owner of project(s):
<ul>
{% for p in profile.ownerprojects %}
    <li>{{p.name}}
{% endfor %}
</ul>
These projects could be downgraded, and indicators (over new membership limits)
could be disabled.
</html>